---
title: "EEE740 Assessment 2 - Evidence‐Based Critical Reflection on Practice"
author: "Mark Ziemann - ID: 219075807"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: readable
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part A - critical reflection on planning, teaching and supporting learning in terms of core knowledge and professional values

1500 words or equivalent

Part A is asking you to take a critically reflective holistic look at your teaching and approaches to student learning. 
In other words, draw on the content on reflective practice e.g. Kolb’s model from weeks 7 and 8 to tell a story in which you critically reflect on your teaching practices and student learning. 
Details are below: DONE

* Draw on theories and frameworks of critical reflection to contextualize the reflection with respect to approaches to and levels of reflection. DONE

* Use e.g. Kolb’s model to frame the reflection in terms of planning, teaching and supporting learning including current practice, planned changes to current practice and anticipated outcomes. DONE

* Successful engagement across A1 (design, and plan learning activities) and A2 (teach and support learning). Clear concise comprehensive and critically compelling evidence of engagement across areas A1 and A2. DONE

* Successful engagement in appropriate teaching practices relates to areas of activity (A2) Clear, concise, comrehensive and critically compelling  evidence of successful engagement in appropriate teaching practices related to the areas of activity DONE

* Appropriate knowledge of K1, the subject material, K2 the appropriate learning methods for teaching, learning and assessing in the subject area and at the level of the academic programme and K3, how students learn both generally and within their subject disciplinary areas. USe and value of appropriate learning technologies to support students in achiving learning outcomes. In depth detailed and critical knowledge of K1 K2 and K3. Use and value of learning technologis is clearly and convincingly explained with substantive reference to pedagogical research. There is a clear and convincing explanation of the way in which technologies can supportstudents in achieving learning outcomes DONE

* A commitment to V1, respect individual learners and diverse learning communities and V2 promote participation in Higher Ed and equality of opportunity for learners, and V4 acknowledge the wider context in which higher ed operated recognising the implications for professional practise. Extensive, clear and critically compelling evidence of a commitment to V1, V2 and V4

* Successful incorporation of subject and pedagogic research and/or scholarship within activities, as part of an integrate approach to academic practice. Extensive, clear and critically compelling evidence of the above.

### Response chapter 1

When I came into lecturing in 2018 from a career in research, it was about ten years after I had last done any teaching.
Indeed, before I entered the research workforce I was finishing my Doctoral thesis and doing sessional laboratory demonstrating, occasional guest lectures and taught a new unit on computational biology to a cohort of 16 students. 
This was around 2009.
When I started at Deakin I _thought_ I was a reasonably good teacher. 
I knew a lot about my topic and believed that my teaching experience was enough to manage my first teaching assignment which was a cloud unit (SLE762) which the students are mostly international.
This unit was one of the first that was offered in online mode only by the School of Life and Environmental Sciences (LES).
With _only three weeks_ preparation time for me until the start of the unit in T2 2018, I had to focus on curating the content and designing assesment tasks for the 40 enrolled students.
Obviously the expected learning outcomes were decided upon before my arrival by the course director, who had done a reasonable job putting together a unit guide with satisfactory learning outcomes (2019 unit guide is attached as an appendix). 

Without the wisdom of the importance of active learning, I set upon a fairly bland teaching style that was heavy on content and light on feedback and interaction.
Indeed I was guilty of trying to "cover" as many topics as possible right up until week 11. 
I planned weekly online Q&A sessions on blackboard collaborate but there were few or no attendees most weeks, until a couple of weeks before major assessment deadlines when maybe 15 students would connect.
There were other difficulties as well - such as lack of help from the digital learning team for AV support, lack of appropriate recording equipment/spaces, lack of video editing and inability to schedule online tutorials when all students were available.
On the plus side, there was some good use of the discussion boards.
Students were generally happy that I was responding to their queries by email and posting these anonymised questions on the discussion site.

Survey feedback from students was generally positive, and most students performed well but there were a hard core that seemed not to "get it". 
These students generally did not engage in the interactive sessions and this came back to hurt their results.
There were a few students that had demonstrated only a superficial understanding of the topic, barely above what could be learned by performing internet searches of the topics at hand.
In fact there were several that received cautions or worse, because of blatant copying of material from the internet.
Since the learning materials were delivered by video and there were limited means of accessing feedback outside of the interactive sessions, students has little means to benchmark their knowledge and quality of work.
There were no genuine opportunities for students to network with one another and this was reflected in the discussion board comments. The area for student discussion recorded just one or two comments, while the questions to the Unit Chair were over 50. 
In addition, when discussing with a couple students a year later, once they had begun their major research project I asked about whether the unit had helped them; they responded that mostly no, the unit did not help them.
Upon asking why, I found that it was mostly because we had "covered" material too quickly and with too little discussion of the difficult concepts.
There was just too much new information for these students to take onboard in such a limited time, and with too little reinforcement that the content itself could not be assimilated, let alone put into a form that could be useful to students beyond the immediate goal of passing the next assessment task. 
Up until this time, I had the illusion that I was a good teacher, but with feedback like that it was dawning upon me that students were not getting a genuine education, just going through the motions.
I will get back to what "genuine education" is a bit further down.

While studying for EEE730 (Contextualising learning and teaching in Higher Education), I became familiar with the different theories of learning and began to identify in myself how I learn important knowledge and skills. 
I relate most to Constructivism, Social Learning Theory, Feminism and Humanism.
I realised that my teaching style was severely contradictory to my own learning style .
My teaching style seemed to be driven by the inertia of the moment; to focus on curating the content rather than reinforcing student understanding.
In effect I had (perhaps unconsciously) developed a teaching style that mimicked the teacher centred style I experienced in my bachelor degree in engineering (2001-2005).
While my learning style was centred around quiet reading/contemplation, group problem solving and practise (self assessment), my teaching style was just content piled on more content.

There were two very distinct points in time when my perspectives to teaching were transformed.
First, when studying for EEE730 I watched for the first time the presentation "Confessions of a converted lecturer" by Professor Eric Mazur (2013).
I realised profoundly what I was doing wrong - and I could identify strongly because Mazur had deceived himself that he was doing a good job for six years before he recognised that his teacher-centred style was stifling the development of a sizable fraction of students.
Indeed, what he realised was that his students were quite good at solving textbook problems but when confronted with conceptual problems, scores were much poorer.
When Mazur changed his teaching style from teacher-centred lectures focused on the "transfer of information", to student centred and interactive sessions he saw that a bigger fraction could understand at a deeper level and retain the knowledge and skills much better.

My second, and more recent transformative epiphany came with reading Biggs and Tang (2011 p16-31) which argues that students learn by _doing_ and the teachers role should be more of a facilitator; enabling activities and assessment tasks that foster interactivity, deep thought and practice with feedback. 
It seems obvious in hindsight, but aligns with lifelong learning; we don't develop lifelong high-value skills only by watching someone else do it, the students need to do it, practise it and be able to quantify their development.
Another reason why this is important is because the university classroom these days is a much more diverse group than decades past, so there is a greater chance for students to have relative strengths and weaknesses.
Without the opportunity to practise and seek feedback in a supportive environment, students with relatively lower starting ability will find it harder to improve.

Both events speak to necessary changes in the the education design for the unit. By first recognising the desirable pedagogical philosophy (Social Constructivism), then putting in place a pedagogical strategy and practices which enables learning through preparation/completion of assessment tasks and participation in learning activities. 

One thing that did go well in SLE762 was that when I asked students who completed the unit previously they said that their writing improved immensely throughout the three written assessment.
Many students entering this master's degree course have indicated to me that their previous higher education was assesed nearly exclusively by examination (multiple choice and short answer), so it is a good sign that this unit has enabled ESL students to develop confidence in long-form writing in English.
Although this is not something which is mentioned explicitly as an expected learning outcome, but perhaps it can be in future years.
To make the most from this experience, I would like to follow through with some of the ideas which I suggested in a reflection piece in EEE730 which fit with the "Active Experimentation" part of Kolb's experiential learning cycle (which coincidentally is analagous to the scientific research cycle):

* More opportunities for self assessment including online quizzes (K2,K4,K5). The formative assessment was good, however it required a lot of effort from the teaching team to deliver this feedback. Smaller miniquizzes could be a rapid way to test student understanding of key concepts.  

* Allocating students into small study groups for peer review and breaking down the preconception that students are not allowed to collaborate on assessment tasks (because students are wary of running into academic integrity problems) (K2,K3).

* Providing students with exemplars of student work and discussing the good and bad points in class and perhaps in breakout groups (K1).

* Allowing students to undertake at least one of the assignments in groups (K2).

* Relaxing the requirement for the final assignment format and allowing students to customise assessment task so long as it satisfactoriry demonstrates the expected learning objectives (K2,K3).

In addition, based on my learnings in this unit I would suggest the following:

* To cut down on the content covered in lecturer and sharply focus on the troublesome ideas, or threshold concepts which link directly to the expected learning objectives which are strongly aligned with the assessment tasks (K1).
The lecturer can prescribe the reading and then this could be the focus of Q&A in the interactive classes.

* A reduction in the amount of content should involve cutting the number of expected learning outcomes from six to three or four.

* To enhance participation in the discussion sessions by including activities that provide feedback which helps students complete the assessment tasks (K2,K3). For example, students discussing draft work in breakout groups.

Upon reflection there were also parts of the unit that were successful and worth noting here:

* The assessments were on the most part directly relevant to the expected learning objectives of the unit, although there could always be improvement.

* Assessments were about the right difficulty. In terms of the SOLO or Bloom's taxonomy, the first assessment was a bit easy, and the solutions to the short answer questions and miniessys were obtainable from careful examination of the lecture material and application of the concepts, which I think was appropriate because this is likely to be their first Deakin Assignment and possibly the first one completed in English. 
On the other hand assessments two and three were focused on higher level thought processes such as application of concepts, evaluation of scholarly material, and creation of presentations and essays to argue for or against changes in the way processes around scholarly publishing.

* Student support was just about at the right level. As unit chair I facilitated opt-in online tutorials, discussion boards and email.
I also put together on campus opt-in drop in sessions (Burwood & Geelong) at key dates in the calendar before assessment deadlines which were very useful. The one aspect that could have been done better was to foster a stronger network of peer support among students.

* As written assessment makes up 90% of the marks, students steadily improved the quality of their written work, in terms of language but also presentation and use of references.
This has to do with students taking onboard the feedback provided to them from the formative and summative assignments, as well as the effect of practice.

* The oral presentation, worth 10% of the marks was a success in that it appeared that students really put in a good effort.
I've noticed in my previous teaching that students perform at a higher level when they present in front of their peers. 
In this format the lecturer can see clearly the level of understanding a student has on the topic.
Students working in teams to complete this component could be a good way to reinforce this.

* Students adapted quickly to use of technology in this unit, and there is room to experiment with further tools to facilitate peer instruction and interaction.
I didn't previously use polling technology, but the work of Mazur (2013) suggests this could be a powerful way to use technology in the virtual classroom for students to benchmark themselves.
Used together with breakout groups this would be a great way to activate student interaction (Mazur 1996).
BlackBoard Collaborate and Zoom have features to enable polling and breakout groups.

Unfortunately I'm not able to enact this experimentation myself because I am no longer lecturer for SLE762 and my duties have moved to other units. I am in touch regularly with the current lecturer for SLE762 and will be sure to share this piece with them.

If these measures were implemented, I would be looking to find evidence that they are working. 
In order to assess whether these changes to learning activities and peer support improved student understanding, I would be observing an increase in student performance and understanding in the interactive blackboard collaborate sessions, as well as better attendance and overall engagement. 
Next, directly comparing the quality of submitted work, specifically for depth of understanding between years (eg 2020 versus 2019 assignment).
Also hoping that student evaluations would reflect on the value of active learning and greater social interaction on the quality of learning.

## Part B - Evidence that demonstrates ongoing professional development in planning and teaching

1000 words or equivalent

Assessment 2, Part B is asking you to do something that you have never done before. You need to tell us about
your professional development and provide artefacts – that is evidence e.g. courses that you might have taken
– to evidence your professional development.

Critically analyse ongoing professional development with respect to past experience, current
engagement and future plans. You will also need to provide an appropriate range of evidence and
artefacts that demonstrate ongoing professional development, influence and success in planning and
teaching practice. In doing this you might like to consider the following suggestions:

* Make reference to your past professional development activities whilst drawing
appropriately on the research based content from this unit as a part of your description of
your current professional development. Make reference to how your engagement with this
unit has informed your plans for future professional development.

* Draw on the artefacts that you have produced whilst progressing through this unit as a
foundation for evidencing your current professional development. Contextualize this with
evidence from the past and for the future e.g. a plan for professional development moving
forwards.

Evidence in engaging in continuing professional development in subjects/disciplines and their pedagogy incorporating research, scholarship and the evaluation of professional practices. 

Provides an extensive and varied range of evidence and artefacts that demonstrate a strong and clear commitment to ongoing professional development, influence and success in planning and teaching practise

### Response chapter 2

I must admit I cringed a bit when reading this assessment question for the first time. 
Like many academics, I enjoy research over teaching.
To be honest, If I had the choice I wouldn't teach teach at all.
It is however part and parcel of this occupation and an important duty. 
So as with anything else in life, if it is worth doing, it must be done well.
Indeed, in my own experience, I have found teaching more enjoyable if is designed, planned and executed well.
For example, poorly designed assessments are likely to lead to student irritation, confusion and a deluge of emails and discussion queries which requires additional work on the part of the teacher to resolve.

With regard to professional development, like to stay up to date with my content area (computational biology) by attending hands-on workshops and conferences. 
These only have a minor influence on my teaching, but I have learned some useful tactics.
For example, in a computer lab, participants are generally following some recipe and the instructor is describing some of the theory behind each step and why it's useful.
It's sometimes quite complicated, so participants get stuck or left behind quite easily.
The instructors give each student two post-it notes, green and red. 
If the student gets stuck, they put up the red post-it, then the instructor or their assistants can attend to the question/problem and try to solve it.
On the other hand, if the students have completed that part and are ready to move on to the next task, they put up the green post-it.
This works well to regulate the tempo of the workshop; if the instructor sees a wave of red, they know they haven't explained something right.
On the other hand if they see a mojority of green, they know that the majority of the class are "getting it" and they can focus on helping the few who havent put up the green post-it.
At the end of the workshop, attendees are asked to provide some feedback; something they liked and something they didn't on the green and red post-its.
This is a nice way to receive anonymous feedback, which can be used for future improvement.

The next obvious thing to mention is the Graduate Certificate of Higher Education (Learning and Teaching).
I have completed two units; EEE733 Scholarship of Teaching and Learning, and EEE730 Contextualising learning and teaching in Higher Education.
Learnings from these units and from EEE740 especially has transformed my approach to teaching, and what an education really is.
Mazur mentions in his seminar (2013) the famous quote: 

> Education Is What Remains After You Have Forgotten Everything You Learned In School

So we are likely to forget much of the content of this course over time, but we are likely to retain knowledge of the threshold concepts because these shape our attitutes and actions immediately.

With regard to this I would suggest a few threshold concepts I've taken on board:

1. Recognising the theory of learning that resonates with me the most, and asking others about theirs.

2. Learning is more than information transfer - it is the assimilation of this information (declarative and procedural) and building links with existing knowledge that is the difficult part, but is necessary to build meaningful, high value skills.

3. Active learning (doing, practise, discussion and apprenticeship) are more powerful than passive learning (listening) because it stimulates the mind, engages, reinforces and demands contemplation.

From this unit I have also learned more about how technology can be useful for teaching.
In EEE730 were were taught that technologies were not that important, it's the activity that is happening that is important.
I tend to agree with this notion. 
For example if the lecturer is polling students in a seminar, it doesn't really matter which polling tool they are using so long as it does the job.
If students are peer reviewing work in breakout groups I don't mind whether they use Google Docs, MS Word, or specialised tools like Perusall (https://perusall.com/) or FeedbackFruits.
In many cases simple is better.

On the topic of technology, I have been having positive feedback from students in SLE712 Molecular Biology and Bioinformatics Techniques with the use of GitHub.
GitHub.com is a website use by software developers to keep track of changes in a software program, but I'm finding it quite useful to host all my documents (learning materials, assignments and other resources).
Students can ask questions and join a discussion with the "issues" feature.
Students can create their own content on GitHub including software and documents.
When students work in teams, each contribution is recorded, so the assessor can give grades based on the final product of the team, but also dig into see how intellectually important each team members contribution is.
In SLE762 I am asking students to develop on their data analysis scripts/reports using GitHub and this accounts for one fifth of the grade.
Indeed, the work I am writing today is developed using GitHub, so you will be able to see how the work has changed over time just by visiting the [public repository](https://github.com/markziemann/gche) and looking at the commit history.
And this will be available on the internet for as long as GitHub exists or I decide to take it down.
I am not the first to bring GitHub into the classroom, there are other examples of educators running their entire courses via GitHub (eg Bryan 2020).
I look forward to investigating more applications of this tool in future, especially as it relates to fostering active learning.

In terms of things I would like to work on personally, I would like to use what I have learned in EEE730 and EEE740 develop better large-group teaching skills.
I was campus coordinator for SLE115 in T1, 2019 which involved 125 students and the teaching style employed in lectures was not very interactive. 
I would like to learn more strategies and tactics in order to engage students in lectures by making it a more active experience.
To address this, I could attend workshops designed for large group instruction, or to enquire with other lecturers about techniques that worked for them.
In my school there currently is a unit chair in chemistry which has several hundred students, who I could ask for tactics, to attend one of their lectures, or even to become my teaching mentor.

On the topic of mentoring, my current mentor is the course director of the Masters in Biotechnology course but I don't think we ever specifically discussed methods for active learning before in any detail, so there is something I can bring up in our next meeting.

In trimester 2, I will be campus coordinator for a unit where the Unit Chair is based in Burwood. They have a bit focus on contructive alignment and active learning and I look forward to learning from them.

In terms of Scholarship of Teaching and Learning, in EEE733 I focused on the issues around fairness in assessment and whether students and staff in LES liked the idea of blind marking. 
I found that both staff and students thought blind marking improved fairness in assessment and both groups suppported a move towards blind marking (Ziemann, 2019).
I raised the issue with DUSA, although the body has not yet made any additional actions on this topic (I think they may have more pressing matters in hand at the moment given the current COVID-19 pandemic situation).
It would be good at some point to reactivate this project and seek greater student and staff survey input across more schools and faculties.
On the other hand these activities are very time consuming and in my view at least these endeavours are not as important to the LES school (and my prospects for career advancement) as research papers and grants.
I may be wrong.

There are also many teaching workshops and conferences that one can attend, however I must be honest that I very rarely engage in these types of workshops.
It looks as if I will be teaching in all three trimesters this year 2020 and as such there just won't be enough time to fit in all-day conferences and endless talkfests in addition to my research and other duties. 

Last year I did however attend such a workshop (13th August 2019) hosted by Dr Madeleine Schultz on the topic of "Towards assessment of employability skills" (because Dr Schultz is a very respected teacher in LES). 
I think some of the topic covered in that workshop are still part of my teaching, including designing assessments that are developing real world skills and aligned with the unit and course expected learning outcomes.

On the 16th June, there is an upcoming SEBE Induction for new Unit Chairs and new teaching /lecturing staff via Zoom. Although it is designed for new staff, I think I could benefit by attending and learning a bit more about the newer features of cloudDeakin and some of the procedural/administration changes in recent times.

I will finish with a bit of a summary about where I see myself in five years time.
In five years, I anticipate that I will still be teaching.
Whereas my first two years at Deakin involved teaching four different units, I hope that in five years time I will be dedicated to the continued development and refinement of just one or two units.
I look forward to developing better skills around building classroom environments that enable free dialogue and student interaction, especially in larger groups.

### References
Biggs, J and Tang, C 2011, _Teaching for Quality Learning at Universit_, 4th Edition.
Open University Press, England.

Bryan, J 2020, _Happy Git and GitHub for the useR_, Ebook, Retrieved 7th June 2020, <https://happygitwithr.com/>.

Fiksel J, Jager LR, Hardin, JS & Taub MA (2019) Using GitHub Classroom To Teach Statistics, Journal of Statistics Education, 27:2, 110-119, DOI: 10.1080/10691898.2019.1617089.

Mazur, E 1996, _Peer Instruction: A User's Manual_,  Benjamin Cummings Publishing, San Francisco, CA.

Mazur, E 2013, _Confessions of a Converted Lecturer_. Retrieved 2 May 2020, <https://www.youtube.com/watch?v=92O6NlOGt1o>.

Ziemann, M (2019) Student and staff perceptions of fairness in assessment and feedback practices. Retrieved 7th June 2020, <https://doi.org/10.5281/zenodo.3460061>.
